[Exposed=*]
interface ReadableStreamBYOBRequest {
    readonly attribute ArrayBufferView? view;

    // FIXME: Implement
    // undefined respond([EnforceRange] unsigned long long bytesWritten);
    // undefined respondWithNewView(ArrayBufferView view);
};
